### ISSUE TITLE
Podcast types not showing up

### ISSUE THREAD

**Issue by eudaimonstro** [Razorcake/razorcake#3]
After you select podcast as the story type in the create story menu, the 3 different types of podcasts aren't available to be selected

**Comment by eudaimonstro** [comment]
![selection_005](https://cloud.githubusercontent.com/assets/5083012/5822008/3c7f21f8-a085-11e4-8d1f-cc0f0b7763f5.png)

**Comment by toddtay** [comment]
No looks good
